### ISSUE TITLE
Missing “New 3D Map View”

### ISSUE THREAD

**Issue by juanmanuelrq** [conda-forge/qgis-feedstock#89]
I was really curious about the new 3D-Map-View function of QGIS3. Now, finally, QGIS3 just released but I'm missing the 3D Map View! It should be at View -> New 3D Map View but it isn't.

**Comment by gillins** [comment]
@ceholden do you know why we currently build with `WITH_3D=FALSE` (https://github.com/conda-forge/qgis-feedstock/blob/master/recipe/build.sh#L45) ? I suspect this controls the 3d functionality. Maybe not all the needed `qt` libs are available for this?

**Comment by SrNetoChan** [comment]
@gillins I think you are right and PyQt Webkit is needed. I will give it a try once the recent version build is green and merged.

**Comment by SrNetoChan** [comment]
This one is fixed at least for QGIS 3.16 on Linux. Can someone please test on Windows and Mac?

**Comment by jakimowb** [comment]
I was able to upgrade to 3.16 (`conda upgrage qgis -c conda-forge`) on macOS 11.0.1. After starting it from the conda shell, the QGIS symbol appears in the Dock, but the QGIS window never showed up, although my system settings allow to install unsigned applications.

For Windows the latest conda-forge QGIS is still 3.14.

**Comment by SrNetoChan** [comment]
@jakimowb we can close this one, right? @juanmanuelrq have you tried with the most recent version of QGIS? should be fixed.

**Comment by juanmanuelrq** [comment]
hi @jakimowb , I have not tried it, I install qgis without anaconda

**Comment by SrNetoChan** [comment]
Closing this one. I have tested in Windows Mac and Linux.

**Comment by jakimowb** [comment]
Thanks @SrNetoChan, I tested it on windows 10 where it worked fine as well 👍 

On macOS I still experience the problems described [described here](https://github.com/conda-forge/qgis-feedstock/pull/154#issuecomment-752043164):

In an fresh conda installation, `conda install qgis -c conda-forge` still install  
````
qgis               conda-forge/osx-64::qgis-3.14.0-py38h1f41940_1
````
it can be started, but is build without 3D Maps. Calling `conda update qgis -c conda-forge` did not update to 3.16 (curiously opposing to my (previous comment)[https://github.com/conda-forge/qgis-feedstock/issues/89#issuecomment-736218969]).

I was able to enforce QGIS 3.16 by `conda install qgis=3.16.3 -c conda-forge`, but this still 
required to set `export QT_MAC_WANTS_LAYER=1` for makeing the GUI visible.

**Comment by SrNetoChan** [comment]
Are you creating separate environments? What version of mac are you trying?

3.16.2 worked fine on my Catalina VM

**Comment by gillins** [comment]
@jakimowb I agree that creating separate environments would be good. So with `QT_MAC_WANTS_LAYER=1` does the 3D stuff work ok?

`QT_MAC_WANTS_LAYER=1` is needed by all Qt apps on Big Sur (see https://bugreports.qt.io/browse/QTBUG-87014). I was thinking it was best to wait for this to be fixed on Qt rather than doing anything here as I'm not sure what setting this on other versions of OSX might break... Do other Big Sur users have any thoughts on this?

**Comment by jakimowb** [comment]
@SrNetoChan I tested on macBook Pro with Intel Core i5 and macOS Big Sur 11.1
@gillins yes, with `QT_MAC_WANTS_LAYER=1` I can start QGIS 3.16 (with 3D) in the default and an explicit defined conda environment. But, besides the Qt environmental variable, it is necessary to enforce the latest version available (`qgis=3.16.3`), because: 
* `install qgis -c conda-forge` installs 3.14, and
* `install qgis=3.16 -c conda-forge` installs 3.16.1 (instead of 3.16.3) and raises an error

**Comment by jakimowb** [comment]
I don't know if this is possible, but until the QT vbug is fixed, it could be helpful to mention the  `QT_MAC_WANTS_LAYER=1` in the QGIS installation script.

**Comment by gillins** [comment]
@jakimowb What happens if you try: `conda create -n testenv -c conda-forge qgis` ?

**Comment by jakimowb** [comment]
@gillins `conda create -n testenv -c conda-forge qgis` created me a 
python 3.9 environment with QGIS 3.16.3, which runs after setting `QT_MAC_WANTS_LAYER=1`:

<details>
  <summary>Click to expand conda list</summary>
  
```bash
boost-cpp                 1.74.0               he5d75e3_0    conda-forge
brotlipy                  0.7.0           py39hcbf5805_1001    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0            he8db5a5_1006    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cffi                      1.14.4           py39h7786acb_1    conda-forge
cfitsio                   3.470                h01dc385_7    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
coverage                  5.3.1            py39hcbf5805_1    conda-forge
cryptography              3.3.1            py39h79a2c39_1    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
dbus                      1.13.6               h0c50699_1    conda-forge
exiv2                     0.27.1               ha4feea6_0    conda-forge
expat                     2.2.9                hb1e8313_2    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.5             h0b31af3_1002    conda-forge
future                    0.18.2           py39h6e9494a_3    conda-forge
gdal                      3.1.4            py39h906d53f_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hc1004f4_3    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.66.4               h22858aa_1    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icu                       67.1                 hb1e8313_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
kealib                    1.4.14               h82515a5_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang                  10.0.1          default_hf57f61e_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgdal                   3.1.4                hd7bf8dc_0    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_16    conda-forge
libgfortran5              9.3.0               h6c81a4c_16    conda-forge
libglib                   2.66.4               h7424822_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8ca2c65_1012    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     12.3                 h7049927_3    conda-forge
libprotobuf               3.14.0               hfd3ada9_0    conda-forge
libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
libspatialite             5.0.0                hc85de81_0    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtasn1                  4.14                 h01d97ff_0    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp                   1.1.0                hd89b0c2_4    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h2c6e4a5_2    conda-forge
libxslt                   1.1.33               hfed2d9b_1    conda-forge
libzip                    1.7.3                hccd5f62_0    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                1.1.1            py39hcbf5805_3    conda-forge
mock                      4.0.3            py39h6e9494a_1    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hfb8f7af_2    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nose2                     0.9.2                      py_0    conda-forge
nspr                      4.29                 hbc8d48c_1    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.19.5           py39he588a01_1    conda-forge
openjpeg                  2.3.1                h6cbf5cd_3    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
owslib                    0.21.0             pyhd8ed1ab_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
poppler                   0.89.0               h3232a60_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 he852019_3    conda-forge
proj                      7.1.1                h45baca5_3    conda-forge
psycopg2                  2.8.6            py39h79a2c39_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyproj                    2.6.1.post1      py39hd525a1d_3    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt-impl                 5.12.3           py39hef7122c_7    conda-forge
pyqt5-sip                 4.19.18          py39hd8f94c5_7    conda-forge
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyqtwebkit                5.212            py39hd2546b8_1    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
python                    3.9.1           h1d169a7_3_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1            py39hcbf5805_2    conda-forge
qca                       2.2.1                hc763db3_3    conda-forge
qgis                      3.16.3           py39h8707900_0    conda-forge
qjson                     0.9.0             hc763db3_1006    conda-forge
qscintilla2               2.11.2           py39h00c7726_4    conda-forge
qt                        5.12.9               h717870c_0    conda-forge
qtkeychain                0.11.1               h80aacfe_0    conda-forge
qtlocation                5.12.9               hb1e8313_0    conda-forge
qtserialport              5.9.8                hc763db3_1    conda-forge
qtwebkit                  5.212                hfa2e8d5_0    conda-forge
qwt                       6.1.5                h2815f34_0    conda-forge
qwtpolar                  1.1.1                h2815f34_7    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tiledb                    2.1.6                h6a9efa5_1    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tzcode                    2020f                h35c211d_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xerces-c                  3.2.3                h0a0444a_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge

```

</details>

**Comment by gillins** [comment]
Great! Usually best to install into a new env as you may have packages installed that conflict with latest `qgis`...

**Comment by SrNetoChan** [comment]
Is there something we need to do about this one?

**Comment by gillins** [comment]
No I don't think so. Was leaving it open as I'm still now sure what to do with `QT_MAC_WANTS_LAYER=1` on Big Sur, but this is probably better handled over at qt-feedstock so all Qt apps work...

**Comment by SrNetoChan** [comment]
> No I don't think so. Was leaving it open as I'm still now sure what to do with `QT_MAC_WANTS_LAYER=1` on Big Sur, but this is probably better handled over at qt-feedstock so all Qt apps work...

Should we open a ticket there?

**Comment by gillins** [comment]
> Should we open a ticket there?

Maybe. According to https://bugreports.qt.io/browse/QTBUG-87014 it has been fixed in Qt 5.12.11 but conda-forge is still on 5.12.9. Do you feel like putting in a Qt PR to update to 5.12.11 and we'll take it from there?

**Comment by SrNetoChan** [comment]
> > Should we open a ticket there?
> 
> Maybe. According to https://bugreports.qt.io/browse/QTBUG-87014 it has been fixed in Qt 5.12.11 but conda-forge is still on 5.12.9. Do you feel like putting in a Qt PR to update to 5.12.11 and we'll take it from there?

I can definitely try!

**Comment by SrNetoChan** [comment]
Seems that 5.12.11 is not available for download, yet ... Or maybe related to the fact that QT LTS will no longer be available as open source [1]?

[1] - https://www.theregister.com/2021/01/05/qt_lts_goes_commercial_only/

**Comment by gillins** [comment]
Will be available first half of 2021:

https://wiki.qt.io/Qt_5.12_Release

I hope they make it soon - not having Big Sur support will be quite a problem for some users.
